### ISSUE TITLE
Cassandra has schema less

### ISSUE THREAD

**Issue by ashtan** [Pita/ueberDB#84]
As the datastax claimed  that Cassandra has schema less No Sql Database.
If I suppose create the below structure of Table .
CREATE TABLE track_by_artist (
  artist text,
  track_id uuid,
  genre text,
  music_file text,
  track text,
  track_length_in_seconds int,
  PRIMARY KEY (artist, track_id)
) WITH
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  index_interval=128 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  populate_io_cache_on_flush='false' AND
  default_time_to_live=0 AND
  speculative_retry='99.0PERCENTILE' AND
  memtable_flush_period_in_ms=0 AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'LZ4Compressor'};

In case of CQL  
then, we want to insert any non exist column in above declared table structure  using CQL or via java client.
inserting the another column metadata in above table using CQL insert  command
INSERT INTO track_by_artist (artist,metadata) VALUES (' Woody Guthrie & Jack Elliott','some extra info about music or movie') ;
Bad Request: Unknown identifier metadata

if any other way to insert using thrift or java diver then please let me know .  if am i wrong then correct me. 

thanks in Advance!

**Comment by JohnMcLear** [comment]
cc @mrvisser

**Comment by mrvisser** [comment]
Hey, sorry for the delay.

Since CQL3, Cassandra isn't really schema-less anymore. You should use an alter statement to add a column to the table:

http://docs.datastax.com/en/cql/3.0/cql/cql_reference/alter_table_r.html

Additionally, there is the `WITH COMPACT STORAGE` property that can be used to store data in the old schema-less model and underlying storage structure. When Cassandra shifted from Thrift/CQL2 to CQL3, DataStax left this helpful blog post to help bridge people from Thrift/CQL2 and schemaless design to CQL3:

http://www.datastax.com/dev/blog/thrift-to-cql3

Hope that helps.

**Comment by JohnMcLear** [comment]
Anything we need to change in the code/docs?

**Comment by mrvisser** [comment]
I don't think so. AFAICT this is just a general question about Cassandra. I'd vote to close it as it doesn't really have anything to do with ueberdb.
